#!/bin/zsh

echo "Patching binutils..."
sh -c "cd binutils-${V_BINUTILS} && patch -p1 < ../../patches/binutils/129_multiarch_libpath.patch"

APPEND_TOOLLIBDIR=yes
export APPEND_TOOLLIBDIR

mkdir binutils-build
mkdir binutils-install
cd binutils-build
../binutils-${V_BINUTILS}/configure \
    --prefix=/usr/local/xenial-toolchain \
    --program-prefix=aarch64-xenial-linux-gnu- \
    --target=aarch64-linux-gnu \
    "--with-pkgversion=GNU Binutils for Ubuntu Xenial Aarch64 16.04" \
    --enable-poison-system-directories \
    --with-sysroot=/usr/local/xenial-toolchain/sys-root \
    --disable-nls \
    --enable-lto \
    --disable-werror
make -j3
DESTDIR=$PWD/../binutils-install make install
cd ../binutils-install
