#!/bin/zsh

rm -rf tree-install
mkdir tree-install
rsync gcc-install/ tree-install -a --copy-links
rsync binutils-install/ tree-install -a --copy-links
rsync sysroot-install/ tree-install -a --copy-links
rsync gdb-install/ tree-install -a --copy-links
du -hs .

pushd tree-install
strip usr/local/xenial-toolchain/bin/*
strip usr/local/xenial-toolchain/aarch64-*/bin/*
find usr/local/xenial-toolchain/libexec -type f |xargs strip
popd

du -hs .
